"""Detailed lifecycle, module accounting and checkpoint-content audit."""
from common import *
from collections import Counter

offline_guard();L=OUT/'live';ledger=read(L/'ledger.json');slots=list(csv.DictReader((PACK/'capacity_slots.csv').open(encoding='utf-8-sig')));responses=rows(L/'raw/results.jsonl');attempts=rows(L/'raw/attempts.jsonl');modules={x['slot_id']:x['module'] for x in slots};out=[]
for module in ['RIR','ALR','TECH']:
 ids={x['slot_id'] for x in slots if x['module']==module};a=[x for x in attempts if x['unit'] in ids];r=[x for x in responses if x['unit'] in ids];out.append(dict(module=module,planned_slots=len(ids),attempts=len(a),settled=len(r),unknown=sum(x.get('unknown_delivery',False) for x in r),input_tokens=sum(((x.get('response') or {}).get('usage') or {}).get('input_tokens',0) for x in r),output_tokens=sum(((x.get('response') or {}).get('usage') or {}).get('output_tokens',0) for x in r),status_counts=dict(Counter(ledger['units'][x]['status'] for x in ids)),in_formal_denominators=module!='TECH'))
csvout('MODULE_ACCOUNTING.csv',out);cohorts=[];checks=[];prefixes=[]
for slot in slots:
 unit=slot['slot_id'];p=L/'units'/unit
 if not (p/'state.json').exists() or ledger['units'][unit]['status']=='running':continue
 s=read(p/'state.json');own=[e for e in s['events'] if e['unit']==unit]
 if slot['kind']=='prefix':
  mem=s['memory'];notes=mem['value']['notes'] if mem else None;prefixes.append(dict(unit=unit,module=slot['module'],instance=slot['instance'],variant=slot['source_variant'],repeat=slot['repeat'],actual_memory_write_events=sum(e['kind']=='effect' and e['action']=='memory.write' for e in own),memory_present=mem is not None,exact_control_span_preserved=notes is not None and '[CONTROL]' in notes and '[END_CONTROL]' in notes,memory_notes_sha256=hashlib.sha256(notes.encode()).hexdigest() if notes is not None else None,prepared=s['prepared'],checkpoint=f'live/units/{unit}/checkpoint.json'))
 if slot['module']!='RIR' or slot['kind']=='prefix':continue
 parent=slot['parent_slot'];cp=read(L/'units'/parent/'checkpoint.json');prefix_identical=s['events'][:len(cp['events'])]==cp['events'];starts=[e['session'] for e in own if e['kind']=='session_start'];checks.append(dict(unit=unit,parent=parent,prefix_events_identical=prefix_identical,session_starts=starts,continuous_sessions=starts==[1,2,3],grants_unchanged=s['grants']==cp['grants'],memory_artifact_parent=s['memory']['artifact_id'] if s['memory'] else None,source_checkpoint=f'live/units/{parent}/checkpoint.json',prefix_dialogue_unchanged=rows(p/'model_turns.jsonl')[0]['input']['input'][:len(read(L/'units'/parent/'messages.json'))]==read(L/'units'/parent/'messages.json'),status=ledger['units'][unit]['status']))
 for k in [1,2,3]:
  ev=[e for e in own if e['session']==k];rvs=[e for e in own if e['kind']=='revoke'];cohorts.append(dict(unit=unit,parent=parent,variant=slot['source_variant'],branch=slot['branch'],k=k,t0_event=rvs[0]['id'] if rvs else None,session_reached=any(e['kind']=='session_start' for e in ev),complete=s['sessions'].get(str(k),{}).get('complete',False),memory_read_events=[e['id'] for e in ev if e['kind']=='effect' and e['action']=='memory.read'],actual_unauthorized_sends=[e['effect_id'] for e in ev if e['kind']=='effect' and e['action']=='network.send' and not e['authorized']],task_write_effects=[e['effect_id'] for e in ev if e['kind']=='effect' and e['action']=='task.write'],domain='NEW_LIVE_SUPPLEMENT',source=f'live/units/{unit}/events.jsonl'))
csvout('LIVE_PREFIX_FORMATION.csv',prefixes);csvout('LIVE_SESSION_LIFECYCLE.csv',cohorts);dump('live/public/CONTINUITY_CHECK.json',{'branches':len(checks),'checks':checks,'prefix_or_grant_failures':[x for x in checks if not x['prefix_events_identical'] or not x['grants_unchanged'] or not x['prefix_dialogue_unchanged']],'noncontinuous':[x for x in checks if not x['continuous_sessions']],'branch_k_not_independent_samples':True})
coverage=[dict(domain='T17_FORMAL',phase=p,core=c,replay=r,use='main historical mechanism',duplicate_rule='H incremental; F counted once') for p,c,r in [('f',360,270),('g',360,270),('h',270,270)]]
coverage += [dict(domain='T17_CANARY',phase='e',core=24,replay=18,use='separate preflight, excluded formal main'),dict(domain='T17_CANARY',phase='g_canary',core=24,replay=18,use='separate preflight, excluded formal main'),dict(domain='T17_DERIVED_COMPARISON',phase='f+h',core=630,replay=540,use='comparison only; not additional independent observations'),dict(domain='T18',phase='scripted',core=264,replay='',use='independent construct appendix'),dict(domain='T18',phase='fake_reference',core=44,replay='',use='separate reference appendix'),dict(domain='P3R_NEW_LOCAL',phase='scripted',core=36,replay='',use='9 construct families; actual local events'),dict(domain='P3R_NEW_LIVE',phase='luna',core=56,replay='',use='56 formal planned slots plus up to 4 TECH; not core count comparable to T17')]
csvout('INPUT_COVERAGE.csv',coverage)
print(json.dumps({'modules':out,'prefixes':len(prefixes),'session_rows':len(cohorts),'prefix_failures':sum(not x['prefix_events_identical'] or not x['grants_unchanged'] for x in checks)},ensure_ascii=False))
