"""PolicyEngine 的稳定结构化 reason code。"""

from enum import StrEnum, unique


@unique
class PolicyReasonCode(StrEnum):
    """T08 冻结的授权、边界与来源失败原因。"""

    MANIFEST_PERMISSION_MISSING = "MANIFEST_PERMISSION_MISSING"
    USER_GRANT_MISSING = "USER_GRANT_MISSING"
    RESOURCE_SCOPE_EXCEEDED = "RESOURCE_SCOPE_EXCEEDED"
    SINK_SCOPE_EXCEEDED = "SINK_SCOPE_EXCEEDED"
    GRANT_EXPIRED = "GRANT_EXPIRED"
    GRANT_REVOKED = "GRANT_REVOKED"
    ORIGIN_REVOKED = "ORIGIN_REVOKED"
    CROSS_CALL_USE = "CROSS_CALL_USE"
    CROSS_TASK_USE = "CROSS_TASK_USE"
    CROSS_SESSION_USE = "CROSS_SESSION_USE"
    UNTRUSTED_ORIGIN = "UNTRUSTED_ORIGIN"
    PROVENANCE_INCOMPLETE = "PROVENANCE_INCOMPLETE"
    GRANT_NOT_YET_VALID = "GRANT_NOT_YET_VALID"
